<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * BalanceTransactionDetails Controller
 *
 * @property \App\Model\Table\BalanceTransactionsTable $BalanceTransactions
 * @property \App\Model\Table\UsersTable $Users
 * @property \App\Model\Table\BalanceSenderDetailsTable $BalanceSenderDetails
 * @property \App\Model\Table\BalanceReceiverDetailsTable $BalanceReceiverDetails
 *
 * @method \App\Model\Entity\BalanceTransactionDetail[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class BalanceTransactionsController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Users');
        $this->loadModel('BalanceTransactions');
        $this->loadModel('BalanceSenderDetails');
        $this->loadModel('BalanceReceiverDetails');

        $this->loadComponent('Aa');
    }

    function checkToken()
    {
        $user = $this->Aa->user_for_token($this);
        return $user['id'];
    }

    public function test()
    {

        $send_items = $this->BalanceSenderDetails
            ->find()
            ->where(['sender_user_id' => $this->checkToken()])
            ->contain(['Users']);
        $this->set([
            'data' => $send_items,
            '_serialize' => ['data']
        ]);
    }

    public function index()
    {
        $this->request->allowMethod('get');
        if ($this->checkToken()) {
//            -----------------------------------------------Check for admin only-----------------------------
            $admin = $this->Users->get($this->checkToken());
            if ($admin->get('parent_id') == null) {
                $item = $this->BalanceTransactions
                    ->find()
                    ->contain('Users');
                $this->set([
                    'item' => $item,
                    'status' => true,
                    '_serialize' => ['item', 'status']
                ]);
            } else {
                $item = $this->BalanceTransactions
                    ->find()
                    ->where(['user_id' => $this->checkToken()]);
                $this->set([
                    'item' => $item,
                    'status' => true,
                    '_serialize' => ['item', 'status']
                ]);
            }

        } else {
            $this->set([
                'message' => 'Invalid user account',
                'status' => false,
                '_serialize' => ['message', 'status']
            ]);
        }
    }

    public function view()
    {
        $this->request->allowMethod('get');
        if ($this->checkToken()) {
            $admin = $this->Users->get($this->checkToken());
            if ($admin->get('parent_id') == null) {
                $key = $this->BalanceTransactions->get($this->request->query('key'));
                $send_items = $this->BalanceSenderDetails
                    ->find()
                    ->where(['sender_user_id' => $key->get('user_id')])
                    ->contain(['Users']);

                $received_items = $this->BalanceReceiverDetails
                    ->find()
                    ->where(['receiver_user_id' => $key->get('user_id')])
                    ->contain(['Users']);


                $this->set([
                    'send' => $send_items,
                    'received' => $received_items,
                    '_serialize' => ['send', 'received']
                ]);
            } else {
                $send_items = $this->BalanceSenderDetails
                    ->find()
                    ->where(['sender_user_id' => $this->checkToken()])
                    ->contain(['Users']);
                $received_items = $this->BalanceReceiverDetails
                    ->find()
                    ->where(['receiver_user_id' => $this->checkToken()])
                    ->contain(['Users']);

                $this->set([
                    'send' => $send_items,
                    'received' => $received_items,
                    '_serialize' => ['send', 'received']
                ]);
            }
        } else {
            $this->set([
                'message' => 'Invalid token',
                'status' => false,
                '_serialize' => ['status', 'message']
            ]);
        }
    }


    function checkSenderBalance(): int
    {
        $user = $this->Aa->user_for_token($this);
        if ($user) {
            $idA = $this->BalanceTransactions->find()->select('id')
                ->where([
                    'user_id' => $user['id']
                ]);
            $id = 0;
            foreach ($idA as $row) {
                $id = $row->id;
            }
            return $id;
        }
        return 0;
    }

    function checkReceiverBalance(): int
    {
        $idA = $this->BalanceTransactions->find()->select('id')
            ->where([
                'user_id' => $this->request->getData('partner_user_id')
            ]);
        $id = 0;
        foreach ($idA as $row) {
            $id = $row->id;
        }
        return $id;
    }

    public function parent()
    {
        $id = $this->Aa->user_for_token($this);
        $user = $this->Users->get($id['id']);
        $parent_user = $this->Users->get($user['parent_id']);
        $this->set([
            'id' => $parent_user['id'],
            'username' => $parent_user['username'],
            '_serialize' => ['id', 'username']
        ]);
    }


    public function ConfirmBalance()
    {
        $confirmSender = $this->BalanceTransactions->get($this->checkSenderBalance());
        $confirmSender->set([
            'payable' => $confirmSender->get('payable') - $this->request->getData('paid'),
        ]);

        $confirmReceiver = $this->BalanceTransactions->get($this->checkReceiverBalance());
        $confirmReceiver->set([
            'receivable' => $confirmReceiver->get('receivable') - $this->request->getData('paid'),
            'received' => $confirmReceiver->get('received') + $this->request->getData('paid')
        ]);
        return $this->BalanceTransactions->save($confirmSender) && $this->BalanceTransactions->save($confirmReceiver);
    }

    private function balanceTransactionDetails()
    {
        $tnx_id = bin2hex(random_bytes(5));

        $balanceTransactionSender = $this->BalanceTransactions->get($this->checkSenderBalance());
        $balanceSenderDetails = $this->BalanceSenderDetails->newEntity();
        $balanceSenderDetails->set([
            'transaction' => $tnx_id,
            'user_id' => $this->request->getData('partner_user_id'),
            'sender_user_id' => $this->checkToken(),
            'sent' => $this->request->getData('paid'),
            'payable' => $balanceTransactionSender->get('payable'),
            'receivable' => $balanceTransactionSender->get('receivable'),
            'status' => true
        ]);

        $balanceTransactionReceiver = $this->BalanceTransactions->get($this->checkReceiverBalance());
        $balanceReceiverDetails = $this->BalanceReceiverDetails->newEntity();
        $balanceReceiverDetails->set([
            'transaction' => $tnx_id,
            'receiver_user_id' => $this->request->getData('partner_user_id'),
            'user_id' => $this->checkToken(),
            'received' => $this->request->getData('paid'),
            'payable' => $balanceTransactionReceiver->get('payable'),
            'receivable' => $balanceTransactionReceiver->get('receivable'),
            'status' => true
        ]);
        if ($this->ConfirmBalance()) {
            return
                $this->BalanceSenderDetails
                    ->save($balanceSenderDetails) &&
                $this->BalanceReceiverDetails
                    ->save($balanceReceiverDetails);
        } else {
            return 0;
        }
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $this->request->allowMethod('post');
        if ($this->checkReceiverBalance()) {
            if ($this->checkSenderBalance()) {

                if ($this->balanceTransactionDetails()) {
                    $this->set([
                        'message' => 'Send transactions request successful',
                        'status' => true,
                        '_serialize' => ['message', 'status']
                    ]);
                } else {
                    $this->set([
                        'message' => 'Send transactions request unsuccessful',
                        'status' => false,
                        '_serialize' => ['message', 'status']
                    ]);
                }
            } else {
                $this->set([
                    'message' => 'Invalid user account',
                    'status' => false,
                    '_serialize' => ['message', 'status']
                ]);
            }
        } else {
            $this->set([
                'message' => 'Invalid partner account',
                'status' => false,
                '_serialize' => ['message', 'status']
            ]);
        }
    }


    public function confirm()
    {

    }
}
