<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Servers Controller
 *
 * @property \App\Model\Table\ServersTable $Servers
 *
 * @method \App\Model\Entity\Server[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ServersController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Servers');
        $this->loadModel('Users');
        $this->loadComponent('Aa');
    }


    function checkToken()
    {
        $user = $this->Aa->user_for_token($this);
        return $user['id'];
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index()
    {
        $this->request->allowMethod('get');
        if ($this->checkToken() == 44){
            $server = $this->Servers->find();

            $this->set([
                'server' => $server,
                'status' => true,
                '_serialize' => ['status', 'server']
            ]);
        }else{
            $this->set([
                'message' => 'Invalid user account',
                'status' => false,
                '_serialize' => ['status', 'message']
            ]);
        }
    }


    public function add()
    {
        $this->request->allowMethod('post');
        if ($this->checkToken() == 44){
        $server = $this->Servers->newEntity();
            $server = $this->Servers->patchEntity($server, $this->request->getData());
            if ($this->Servers->save($server)) {
                $this->set([
                    'message' => 'Server generated successful',
                    'status' => true,
                    '_serialize' => ['status', 'message']
                ]);
            }else{
                $this->set([
                    'message' => 'Failed to generate server',
                    'status' => false,
                    '_serialize' => ['status', 'message']
                ]);
            }
        }else{
            $this->set([
                'message' => 'Invalid user account',
                'status' => false,
                '_serialize' => ['status', 'message']
            ]);
        }
    }
}
