<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * ServerRealms Controller
 *
 * @property \App\Model\Table\ServerRealmsTable $ServerRealms
 * @property \App\Model\Table\ServersTable $Servers
 *
 *
 * @method \App\Model\Entity\ServerRealm[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ServerRealmsController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('ServerRealms');
        $this->loadModel('Servers');
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['Servers', 'Realms'],
        ];
        $serverRealms = $this->paginate($this->ServerRealms);

        $this->set(compact('serverRealms'));
    }


    public function servers()
    {
        $servers = $this->Servers->find();

        $this->set([
            'servers' => $servers,
            '_serialize' => ['servers']
        ]);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $this->request->allowMethod('post');
        $serverRealm = $this->ServerRealms->newEntity();

        $serverRealm->set([
            'server_id'=> $this->request->getData('server'),
            'realm_id'=> $this->request->getData('realm')
        ]);

        if ($this->ServerRealms->save($serverRealm)) {
            $this->set([
                'message' => 'Generated successful',
                'success' => true,
                '_serialize' => ['success','message']
            ]);
        }
        else{
            $this->set([
                'message' => 'failed to generate',
                'success' => false,
                '_serialize' => ['success','message']
            ]);
        }
    }

}
