<?php

namespace App\Controller;

use App\Controller\AppController;

/**
 * TweakRealms Controller
 *
 * @property \App\Model\Table\TweakRealmsTable $TweakRealms
 * @property \App\Model\Table\TweaksTable $Tweaks
 *
 * @method \App\Model\Entity\TweakRealm[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class TweakRealmsController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Tweaks');
        $this->loadModel('Users');

        $this->loadComponent('Aa');
    }


    function checkToken()
    {
        $user = $this->Aa->user_for_token($this);
        return $user['id'];
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index()
    {
        $this->request->allowMethod('get');

        if ($this->checkToken() == 44){
            $this->paginate = [
                'contain' => ['Tweaks', 'Realms'],
            ];
            $tweakRealms = $this->paginate($this->TweakRealms);

            $this->set([
                'tweakRealms' => $tweakRealms,
                'status' => true,
                '_serialize' => ['status', 'tweakRealms']
            ]);
        }else{
            $this->set([
                'message' => 'Invalid token',
                'status' => false,
                '_serialize' => ['status', 'message']
            ]);
        }

    }



    public function tweaks()
    {
        $tweaks = $this->Tweaks->find();

        $this->set([
            'tweaks' => $tweaks,
            '_serialize' => ['tweaks']
        ]);
    }



    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $this->request->allowMethod('post');
        $serverRealm = $this->TweakRealms->newEntity();

        $serverRealm->set([
            'tweak_id' => $this->request->getData('tweak'),
            'realm_id' => $this->request->getData('realm')
        ]);

        if ($this->TweakRealms->save($serverRealm)) {
            $this->set([
                'message' => 'Generated successful',
                'success' => true,
                '_serialize' => ['success', 'message']
            ]);
        } else {
            $this->set([
                'message' => 'failed to generate',
                'success' => false,
                '_serialize' => ['success', 'message']
            ]);
        }
    }
}
